version: '3.8'

services:

  app:
    build: .
    container_name: laravel_app

    volumes:
      - .:/var/www

    ports:
      - "8000:8000"

    depends_on:
      - mysql

    command: php artisan serve --host=0.0.0.0

  mysql:
    image: mysql:8

    container_name: laravel_db

    restart: always

    environment:
      MYSQL_DATABASE: bumdes
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3307:3306"

    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: